const curvePairABI = [
  {
    name: "TokenExchange",
    inputs: [
      { type: "address", name: "buyer", indexed: true },
      { type: "int128", name: "sold_id", indexed: false },
      { type: "uint256", name: "tokens_sold", indexed: false },
      { type: "int128", name: "bought_id", indexed: false },
      { type: "uint256", name: "tokens_bought", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "TokenExchangeUnderlying",
    inputs: [
      { type: "address", name: "buyer", indexed: true },
      { type: "int128", name: "sold_id", indexed: false },
      { type: "uint256", name: "tokens_sold", indexed: false },
      { type: "int128", name: "bought_id", indexed: false },
      { type: "uint256", name: "tokens_bought", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "AddLiquidity",
    inputs: [
      { type: "address", name: "provider", indexed: true },
      { type: "uint256[2]", name: "token_amounts", indexed: false },
      { type: "uint256[2]", name: "fees", indexed: false },
      { type: "uint256", name: "invariant", indexed: false },
      { type: "uint256", name: "token_supply", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "RemoveLiquidity",
    inputs: [
      { type: "address", name: "provider", indexed: true },
      { type: "uint256[2]", name: "token_amounts", indexed: false },
      { type: "uint256[2]", name: "fees", indexed: false },
      { type: "uint256", name: "token_supply", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "RemoveLiquidityOne",
    inputs: [
      { type: "address", name: "provider", indexed: true },
      { type: "uint256", name: "token_amount", indexed: false },
      { type: "uint256", name: "coin_amount", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "RemoveLiquidityImbalance",
    inputs: [
      { type: "address", name: "provider", indexed: true },
      { type: "uint256[2]", name: "token_amounts", indexed: false },
      { type: "uint256[2]", name: "fees", indexed: false },
      { type: "uint256", name: "invariant", indexed: false },
      { type: "uint256", name: "token_supply", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "CommitNewAdmin",
    inputs: [
      { type: "uint256", name: "deadline", indexed: true },
      { type: "address", name: "admin", indexed: true },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "NewAdmin",
    inputs: [{ type: "address", name: "admin", indexed: true }],
    anonymous: false,
    type: "event",
  },
  {
    name: "CommitNewFee",
    inputs: [
      { type: "uint256", name: "deadline", indexed: true },
      { type: "uint256", name: "fee", indexed: false },
      { type: "uint256", name: "admin_fee", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "NewFee",
    inputs: [
      { type: "uint256", name: "fee", indexed: false },
      { type: "uint256", name: "admin_fee", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "RampA",
    inputs: [
      { type: "uint256", name: "old_A", indexed: false },
      { type: "uint256", name: "new_A", indexed: false },
      { type: "uint256", name: "initial_time", indexed: false },
      { type: "uint256", name: "future_time", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "StopRampA",
    inputs: [
      { type: "uint256", name: "A", indexed: false },
      { type: "uint256", name: "t", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    outputs: [],
    inputs: [
      { type: "address", name: "_owner" },
      { type: "address[2]", name: "_coins" },
      { type: "address", name: "_pool_token" },
      { type: "uint256", name: "_A" },
      { type: "uint256", name: "_fee" },
      { type: "uint256", name: "_admin_fee" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    name: "A",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 5289,
  },
  {
    name: "A_precise",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 5251,
  },
  {
    name: "balances",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [{ type: "uint256", name: "i" }],
    stateMutability: "view",
    type: "function",
    gas: 5076,
  },
  {
    name: "get_virtual_price",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 1114301,
  },
  {
    name: "calc_token_amount",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [
      { type: "uint256[2]", name: "amounts" },
      { type: "bool", name: "is_deposit" },
    ],
    stateMutability: "view",
    type: "function",
    gas: 2218181,
  },
  {
    name: "add_liquidity",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [
      { type: "uint256[2]", name: "amounts" },
      { type: "uint256", name: "min_mint_amount" },
    ],
    stateMutability: "payable",
    type: "function",
    gas: 3484118,
  },
  {
    name: "get_dy",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [
      { type: "int128", name: "i" },
      { type: "int128", name: "j" },
      { type: "uint256", name: "dx" },
    ],
    stateMutability: "view",
    type: "function",
    gas: 2654541,
  },
  {
    name: "exchange",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [
      { type: "int128", name: "i" },
      { type: "int128", name: "j" },
      { type: "uint256", name: "dx" },
      { type: "uint256", name: "min_dy" },
    ],
    stateMutability: "payable",
    type: "function",
    gas: 2810134,
  },
  {
    name: "remove_liquidity",
    outputs: [{ type: "uint256[2]", name: "" }],
    inputs: [
      { type: "uint256", name: "_amount" },
      { type: "uint256[2]", name: "_min_amounts" },
    ],
    stateMutability: "nonpayable",
    type: "function",
    gas: 160545,
  },
  {
    name: "remove_liquidity_imbalance",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [
      { type: "uint256[2]", name: "_amounts" },
      { type: "uint256", name: "_max_burn_amount" },
    ],
    stateMutability: "nonpayable",
    type: "function",
    gas: 3519382,
  },
  {
    name: "calc_withdraw_one_coin",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [
      { type: "uint256", name: "_token_amount" },
      { type: "int128", name: "i" },
    ],
    stateMutability: "view",
    type: "function",
    gas: 1435,
  },
  {
    name: "remove_liquidity_one_coin",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [
      { type: "uint256", name: "_token_amount" },
      { type: "int128", name: "i" },
      { type: "uint256", name: "_min_amount" },
    ],
    stateMutability: "nonpayable",
    type: "function",
    gas: 4113806,
  },
  {
    name: "ramp_A",
    outputs: [],
    inputs: [
      { type: "uint256", name: "_future_A" },
      { type: "uint256", name: "_future_time" },
    ],
    stateMutability: "nonpayable",
    type: "function",
    gas: 151834,
  },
  {
    name: "stop_ramp_A",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 148595,
  },
  {
    name: "commit_new_fee",
    outputs: [],
    inputs: [
      { type: "uint256", name: "new_fee" },
      { type: "uint256", name: "new_admin_fee" },
    ],
    stateMutability: "nonpayable",
    type: "function",
    gas: 110431,
  },
  {
    name: "apply_new_fee",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 153115,
  },
  {
    name: "revert_new_parameters",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 21865,
  },
  {
    name: "commit_transfer_ownership",
    outputs: [],
    inputs: [{ type: "address", name: "_owner" }],
    stateMutability: "nonpayable",
    type: "function",
    gas: 74603,
  },
  {
    name: "apply_transfer_ownership",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 116583,
  },
  {
    name: "revert_transfer_ownership",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 21955,
  },
  {
    name: "withdraw_admin_fees",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 137597,
  },
  {
    name: "donate_admin_fees",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 42144,
  },
  { name: "kill_me", outputs: [], inputs: [], stateMutability: "nonpayable", type: "function", gas: 37938 },
  {
    name: "unkill_me",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 22075,
  },
  {
    name: "coins",
    outputs: [{ type: "address", name: "" }],
    inputs: [{ type: "uint256", name: "arg0" }],
    stateMutability: "view",
    type: "function",
    gas: 2160,
  },
  {
    name: "admin_balances",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [{ type: "uint256", name: "arg0" }],
    stateMutability: "view",
    type: "function",
    gas: 2190,
  },
  {
    name: "fee",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2111,
  },
  {
    name: "admin_fee",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2141,
  },
  {
    name: "owner",
    outputs: [{ type: "address", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2171,
  },
  {
    name: "lp_token",
    outputs: [{ type: "address", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2201,
  },
  {
    name: "initial_A",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2231,
  },
  {
    name: "future_A",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2261,
  },
  {
    name: "initial_A_time",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2291,
  },
  {
    name: "future_A_time",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2321,
  },
  {
    name: "admin_actions_deadline",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2351,
  },
  {
    name: "transfer_ownership_deadline",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2381,
  },
  {
    name: "future_fee",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2411,
  },
  {
    name: "future_admin_fee",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2441,
  },
  {
    name: "future_owner",
    outputs: [{ type: "address", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2471,
  },
];

const ERC20ABI = [
  {
    constant: true,
    inputs: [],
    name: "name",
    outputs: [
      {
        name: "",
        type: "string",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_spender",
        type: "address",
      },
      {
        name: "_value",
        type: "uint256",
      },
    ],
    name: "approve",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_from",
        type: "address",
      },
      {
        name: "_to",
        type: "address",
      },
      {
        name: "_value",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "decimals",
    outputs: [
      {
        name: "",
        type: "uint8",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "_owner",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        name: "balance",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "symbol",
    outputs: [
      {
        name: "",
        type: "string",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_to",
        type: "address",
      },
      {
        name: "_value",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "_owner",
        type: "address",
      },
      {
        name: "_spender",
        type: "address",
      },
    ],
    name: "allowance",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    payable: true,
    stateMutability: "payable",
    type: "fallback",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        name: "spender",
        type: "address",
      },
      {
        indexed: false,
        name: "value",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        name: "value",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
];

const makerPsmUsdcABI = [
  {
    inputs: [
      { internalType: "address", name: "gemJoin_", type: "address" },
      { internalType: "address", name: "daiJoin_", type: "address" },
      { internalType: "address", name: "vow_", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: false, internalType: "uint256", name: "value", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "fee", type: "uint256" },
    ],
    name: "BuyGem",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "user", type: "address" }],
    name: "Deny",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "what", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "data", type: "uint256" },
    ],
    name: "File",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "user", type: "address" }],
    name: "Rely",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: false, internalType: "uint256", name: "value", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "fee", type: "uint256" },
    ],
    name: "SellGem",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "usr", type: "address" },
      { internalType: "uint256", name: "gemAmt", type: "uint256" },
    ],
    name: "buyGem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "dai",
    outputs: [{ internalType: "contract DaiAbstract", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "daiJoin",
    outputs: [{ internalType: "contract DaiJoinAbstract", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "usr", type: "address" }],
    name: "deny",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "what", type: "bytes32" },
      { internalType: "uint256", name: "data", type: "uint256" },
    ],
    name: "file",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "gemJoin",
    outputs: [{ internalType: "contract AuthGemJoinAbstract", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "usr", type: "address" }],
    name: "hope",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "ilk",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "usr", type: "address" }],
    name: "nope",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "usr", type: "address" }],
    name: "rely",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "usr", type: "address" },
      { internalType: "uint256", name: "gemAmt", type: "uint256" },
    ],
    name: "sellGem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "tin",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tout",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "vat",
    outputs: [{ internalType: "contract VatAbstract", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "vow",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "wards",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
];

const GEM_JOIN_ABI = [
  {
    inputs: [
      { internalType: "address", name: "vat_", type: "address" },
      { internalType: "bytes32", name: "ilk_", type: "bytes32" },
      { internalType: "address", name: "gem_", type: "address" },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: true,
    inputs: [
      { indexed: true, internalType: "bytes4", name: "sig", type: "bytes4" },
      { indexed: true, internalType: "address", name: "usr", type: "address" },
      { indexed: true, internalType: "bytes32", name: "arg1", type: "bytes32" },
      { indexed: true, internalType: "bytes32", name: "arg2", type: "bytes32" },
      { indexed: false, internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "LogNote",
    type: "event",
  },
  {
    constant: false,
    inputs: [],
    name: "cage",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "dec",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "address", name: "usr", type: "address" }],
    name: "deny",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "usr", type: "address" },
      { internalType: "uint256", name: "wad", type: "uint256" },
    ],
    name: "exit",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "gem",
    outputs: [{ internalType: "contract GemLike", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "ilk",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "usr", type: "address" },
      { internalType: "uint256", name: "wad", type: "uint256" },
    ],
    name: "join",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "live",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "address", name: "usr", type: "address" }],
    name: "rely",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "vat",
    outputs: [{ internalType: "contract VatLike", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "wards",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

const PAUSE_ABI = [
  {
    inputs: [
      { internalType: "uint256", name: "delay_", type: "uint256" },
      { internalType: "address", name: "owner_", type: "address" },
      {
        internalType: "contract DSAuthority",
        name: "authority_",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: true,
    inputs: [
      { indexed: true, internalType: "bytes4", name: "sig", type: "bytes4" },
      { indexed: true, internalType: "address", name: "guy", type: "address" },
      { indexed: true, internalType: "bytes32", name: "foo", type: "bytes32" },
      { indexed: true, internalType: "bytes32", name: "bar", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "wad", type: "uint256" },
      { indexed: false, internalType: "bytes", name: "fax", type: "bytes" },
    ],
    name: "LogNote",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "authority",
        type: "address",
      },
    ],
    name: "LogSetAuthority",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "LogSetOwner",
    type: "event",
  },
  {
    constant: true,
    inputs: [],
    name: "authority",
    outputs: [{ internalType: "contract DSAuthority", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "delay",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "usr", type: "address" },
      { internalType: "bytes32", name: "tag", type: "bytes32" },
      { internalType: "bytes", name: "fax", type: "bytes" },
      { internalType: "uint256", name: "eta", type: "uint256" },
    ],
    name: "drop",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "usr", type: "address" },
      { internalType: "bytes32", name: "tag", type: "bytes32" },
      { internalType: "bytes", name: "fax", type: "bytes" },
      { internalType: "uint256", name: "eta", type: "uint256" },
    ],
    name: "exec",
    outputs: [{ internalType: "bytes", name: "out", type: "bytes" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "plans",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "usr", type: "address" },
      { internalType: "bytes32", name: "tag", type: "bytes32" },
      { internalType: "bytes", name: "fax", type: "bytes" },
      { internalType: "uint256", name: "eta", type: "uint256" },
    ],
    name: "plot",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "proxy",
    outputs: [{ internalType: "contract DSPauseProxy", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "contract DSAuthority",
        name: "authority_",
        type: "address",
      },
    ],
    name: "setAuthority",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "uint256", name: "delay_", type: "uint256" }],
    name: "setDelay",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "address", name: "owner_", type: "address" }],
    name: "setOwner",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

const PROXY_ABI = [
  { inputs: [], payable: false, stateMutability: "nonpayable", type: "constructor" },
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "usr", type: "address" },
      { internalType: "bytes", name: "fax", type: "bytes" },
    ],
    name: "exec",
    outputs: [{ internalType: "bytes", name: "out", type: "bytes" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

const SPELL_ACTION = [
  {
    inputs: [],
    name: "actions",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "description",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "execute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "eta",
        type: "uint256",
      },
    ],
    name: "nextCastTime",
    outputs: [
      {
        internalType: "uint256",
        name: "castTime",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "officeHours",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "placeholderProxyMemory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "psmAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_psmAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_tin",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_tout",
        type: "uint256",
      },
    ],
    name: "setValues",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "tin",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tout",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const PSM_ABI = [
  {
    inputs: [
      { internalType: "address", name: "gemJoin_", type: "address" },
      { internalType: "address", name: "daiJoin_", type: "address" },
      { internalType: "address", name: "vow_", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: false, internalType: "uint256", name: "value", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "fee", type: "uint256" },
    ],
    name: "BuyGem",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "user", type: "address" }],
    name: "Deny",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "what", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "data", type: "uint256" },
    ],
    name: "File",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "user", type: "address" }],
    name: "Rely",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: false, internalType: "uint256", name: "value", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "fee", type: "uint256" },
    ],
    name: "SellGem",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "usr", type: "address" },
      { internalType: "uint256", name: "gemAmt", type: "uint256" },
    ],
    name: "buyGem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "dai",
    outputs: [{ internalType: "contract DaiAbstract", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "daiJoin",
    outputs: [{ internalType: "contract DaiJoinAbstract", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "usr", type: "address" }],
    name: "deny",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "what", type: "bytes32" },
      { internalType: "uint256", name: "data", type: "uint256" },
    ],
    name: "file",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "gemJoin",
    outputs: [{ internalType: "contract AuthGemJoinAbstract", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "usr", type: "address" }],
    name: "hope",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "ilk",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "usr", type: "address" }],
    name: "nope",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "usr", type: "address" }],
    name: "rely",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "usr", type: "address" },
      { internalType: "uint256", name: "gemAmt", type: "uint256" },
    ],
    name: "sellGem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "tin",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tout",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "vat",
    outputs: [{ internalType: "contract VatAbstract", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "vow",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "wards",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
];

const ILK_REGISTRY_ABI = [
  {
    inputs: [
      { internalType: "address", name: "vat_", type: "address" },
      { internalType: "address", name: "dog_", type: "address" },
      { internalType: "address", name: "cat_", type: "address" },
      { internalType: "address", name: "spot_", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "AddIlk",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "usr", type: "address" }],
    name: "Deny",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bytes32", name: "what", type: "bytes32" },
      { indexed: false, internalType: "address", name: "data", type: "address" },
    ],
    name: "File",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bytes32", name: "ilk", type: "bytes32" },
      { indexed: false, internalType: "bytes32", name: "what", type: "bytes32" },
      { indexed: false, internalType: "address", name: "data", type: "address" },
    ],
    name: "File",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bytes32", name: "ilk", type: "bytes32" },
      { indexed: false, internalType: "bytes32", name: "what", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "data", type: "uint256" },
    ],
    name: "File",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bytes32", name: "ilk", type: "bytes32" },
      { indexed: false, internalType: "bytes32", name: "what", type: "bytes32" },
      { indexed: false, internalType: "string", name: "data", type: "string" },
    ],
    name: "File",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "NameError",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "usr", type: "address" }],
    name: "Rely",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "RemoveIlk",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "SymbolError",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "UpdateIlk",
    type: "event",
  },
  {
    inputs: [{ internalType: "address", name: "adapter", type: "address" }],
    name: "add",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "cat",
    outputs: [{ internalType: "contract CatLike", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "class",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "count",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "dec",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "usr", type: "address" }],
    name: "deny",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "dog",
    outputs: [{ internalType: "contract DogLike", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "ilk", type: "bytes32" },
      { internalType: "bytes32", name: "what", type: "bytes32" },
      { internalType: "uint256", name: "data", type: "uint256" },
    ],
    name: "file",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "ilk", type: "bytes32" },
      { internalType: "bytes32", name: "what", type: "bytes32" },
      { internalType: "string", name: "data", type: "string" },
    ],
    name: "file",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "what", type: "bytes32" },
      { internalType: "address", name: "data", type: "address" },
    ],
    name: "file",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "ilk", type: "bytes32" },
      { internalType: "bytes32", name: "what", type: "bytes32" },
      { internalType: "address", name: "data", type: "address" },
    ],
    name: "file",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "gem",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "pos", type: "uint256" }],
    name: "get",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "ilkData",
    outputs: [
      { internalType: "uint96", name: "pos", type: "uint96" },
      { internalType: "address", name: "join", type: "address" },
      { internalType: "address", name: "gem", type: "address" },
      { internalType: "uint8", name: "dec", type: "uint8" },
      { internalType: "uint96", name: "class", type: "uint96" },
      { internalType: "address", name: "pip", type: "address" },
      { internalType: "address", name: "xlip", type: "address" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "symbol", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "info",
    outputs: [
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "symbol", type: "string" },
      { internalType: "uint256", name: "class", type: "uint256" },
      { internalType: "uint256", name: "dec", type: "uint256" },
      { internalType: "address", name: "gem", type: "address" },
      { internalType: "address", name: "pip", type: "address" },
      { internalType: "address", name: "join", type: "address" },
      { internalType: "address", name: "xlip", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "join",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  //   {
  //     inputs: [],
  //     name: "list",
  //     outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
  //     stateMutability: "view",
  //     type: "function",
  //   },
  {
    inputs: [
      { internalType: "uint256", name: "start", type: "uint256" },
      { internalType: "uint256", name: "end", type: "uint256" },
    ],
    name: "list",
    outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "pip",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "pos",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_ilk", type: "bytes32" },
      { internalType: "address", name: "_join", type: "address" },
      { internalType: "address", name: "_gem", type: "address" },
      { internalType: "uint256", name: "_dec", type: "uint256" },
      { internalType: "uint256", name: "_class", type: "uint256" },
      { internalType: "address", name: "_pip", type: "address" },
      { internalType: "address", name: "_xlip", type: "address" },
      { internalType: "string", name: "_name", type: "string" },
      { internalType: "string", name: "_symbol", type: "string" },
    ],
    name: "put",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "usr", type: "address" }],
    name: "rely",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "remove",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "removeAuth",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "spot",
    outputs: [{ internalType: "contract SpotLike", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "update",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "vat",
    outputs: [{ internalType: "contract VatLike", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "wards",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "ilk", type: "bytes32" }],
    name: "xlip",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
];

module.exports = {
  curvePairABI,
  ERC20ABI,
  makerPsmUsdcABI,
  GEM_JOIN_ABI,
  PAUSE_ABI,
  PROXY_ABI,
  SPELL_ACTION,
  PSM_ABI,
  ILK_REGISTRY_ABI,
};
